name: Build OpenJDK 11 for Android

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_android:
    strategy:
      matrix:
        arch: [ "aarch32", "aarch64", "x86", "x86_64" ]
      fail-fast: false

    name: "Build for Android ${{matrix.arch}}"
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt -y install autoconf python2 dh-python unzip zip systemtap-sdt-dev libxtst-dev libasound2-dev libelf-dev libfontconfig1-dev libx11-dev libxext-dev libxrandr-dev libxrender-dev libxtst-dev libxt-dev
    - name: Build with CI build script
      run: bash "ci_build_arch_${{matrix.arch}}.sh"
    - name: Upload JRE build output
      uses: actions/upload-artifact@v4
      with:
        name: 'jre11-${{matrix.arch}}'
        path: jre11*.tar.xz

  pojav:
    needs: build_android
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Get jre11-aarch32
      uses: actions/download-artifact@v4
      with:
        name: jre11-aarch32
        path: pojav
    - name: Get jre11-aarch64
      uses: actions/download-artifact@v4
      with:
        name: jre11-aarch64
        path: pojav
    - name: Get jre11-x86
      uses: actions/download-artifact@v4
      with:
        name: jre11-x86
        path: pojav
    - name: Get jre11-x86_64
      uses: actions/download-artifact@v4
      with:
        name: jre11-x86_64
        path: pojav
    - name: Repack JRE
      run: bash "repackjre.sh" $GITHUB_WORKSPACE/pojav $GITHUB_WORKSPACE/pojav/jre11-pojav
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: jre11-pojav
          path: pojav/jre11-pojav/*
